### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find module

### ISSUE THREAD

**Issue by MASSKAgithub** [PruvoNet/countryIpSpoofer#12]
after installing the module with:
```
npm i country-ip-spoofer
```
what is showing the error:

```
import {createDataTable} from 'country-ip-spoofer/dataTableCreator';
```

**Comment by regevbr** [comment]
The example is not good, you should do `import {createDataTable} from 'country-ip-spoofer/dist/dataTableCreator';` I will fix the readme soon

**Comment by ziyaad30** [comment]
setDataTable(dataSet as DataTable);
             ^^^^^^^

SyntaxError: missing ) after argument list

**Comment by regevbr** [comment]
> setDataTable(dataSet as DataTable); ^^^^^^^
> 
> SyntaxError: missing ) after argument list

Pleas open a new issue with more details
